### PR TITLE
create ghostwriting.md

### PR DESCRIPTION
**Pull request by OpenGlobe**
Product description and agenda outline.  @blacktm - @lanebecker and I discussed trying to expand the product descriptions a bit in order to standardize them - as a first pass, here's something roughed out from the agenda from the upcoming RFP Ghostwriting workshop.  Not sure where to fit exactly in the pages, but thought perhaps you might have some ideas here.  Lane, feel free to expand / edit, or if there's a better home, we can move stuff like this.  Pages seemed like it might be a natural place to start.

### CODE REVIEW

**Comment by blacktm** [comment]
Awesome, looks good. Pages is our sandbox, so we can link it anywhere. I can also see how some content could start here and get "promoted" to [18f.gsa.gov/consulting](https://18f.gsa.gov/consulting/).

**Comment by OpenGlobe** [comment]
Ok, great - for now, am I ok to continue setting up a few more of these and pushing them your way?

**Comment by blacktm** [comment]
Sounds good, have at it.

**Comment by vdavez** [comment]
+1 on doing this, but my main concern is that not every ghostwriting is the same (not even three days!)... Let me share the current version of the "one sheeter.

**Comment by OpenGlobe** [comment]
Ok, sounds good - I'll just push some placeholder items up and let the broader team refine / improve as necessary, if that works for everyone.

**Comment by OpenGlobe** [comment]
Closing this pull request to include new pages...

https://github.com/18F/consulting/pull/13

**Pull request closed without merging**
